# Generated by Django 6.1 on 2026-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL segment — the dashboard is served at /d/<slug>/', max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, default='', help_text='A single emoji shown on the picker card.', max_length=8)),
                ('kind', models.CharField(choices=[('internal', 'Internal — a Django app in this project'), ('proxied', 'Proxied — a separate service on loopback')], default='internal', max_length=10)),
                ('upstream', models.URLField(blank=True, default='', help_text='Proxied dashboards only — the loopback origin it listens on, e.g. http://127.0.0.1:4310. Leave blank for internal ones.', max_length=300)),
                ('health_path', models.CharField(blank=True, default='/', help_text='Proxied dashboards only — path probed for the live/offline badge.', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
