# Generated by Django 6.0.4 on 2026-04-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_value_usd', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrossMtmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('entry_cost', models.FloatField()),
                ('position_size', models.FloatField()),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'effective_until'], name='tracker_cro_asset_bcbf69_idx')],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('segment', models.CharField(choices=[('xlBTC', 'xlBTC'), ('xlETH', 'xlETH'), ('xlUSD', 'xlUSD')], max_length=10)),
                ('wallet_address', models.CharField(default='', max_length=100)),
                ('btc_price', models.FloatField(blank=True, null=True)),
                ('eth_price', models.FloatField(blank=True, null=True)),
                ('colend_supply_usdc', models.FloatField(blank=True, null=True)),
                ('aave_supply_amount', models.FloatField(blank=True, null=True)),
                ('aave_supply_usd', models.FloatField(blank=True, null=True)),
                ('aave_borrow_usdc', models.FloatField(blank=True, null=True)),
                ('aave_health_rate', models.FloatField(blank=True, null=True)),
                ('aave_net_usd', models.FloatField(blank=True, null=True)),
                ('aave_profit', models.FloatField(blank=True, null=True)),
                ('susds_eth_balance', models.FloatField(blank=True, null=True)),
                ('susds_arbi_balance', models.FloatField(blank=True, null=True)),
                ('hl_deposit_usdc', models.FloatField(blank=True, null=True)),
                ('wallet_balance_usd', models.FloatField(blank=True, null=True)),
                ('funding_cumulative', models.FloatField(blank=True, null=True)),
                ('price_diff_hl_bn', models.FloatField(blank=True, null=True)),
                ('cross_mtm_value', models.FloatField(blank=True, null=True)),
                ('pnl_usdc', models.FloatField(blank=True, null=True)),
                ('pnl_native', models.FloatField(blank=True, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('portfolio_value', models.FloatField(blank=True, null=True)),
                ('annualized_return', models.FloatField(blank=True, null=True)),
                ('raw_debank_json', models.TextField(blank=True, null=True)),
                ('scrape_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['segment', 'timestamp'], name='tracker_sna_segment_77a0af_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyPnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('segment', models.CharField(choices=[('xlBTC', 'xlBTC'), ('xlETH', 'xlETH'), ('xlUSD', 'xlUSD')], max_length=10)),
                ('pnl_usdc', models.FloatField(blank=True, null=True)),
                ('pnl_native', models.FloatField(blank=True, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('portfolio_value', models.FloatField(blank=True, null=True)),
                ('annualized_return', models.FloatField(blank=True, null=True)),
                ('funding_total', models.FloatField(blank=True, null=True)),
                ('rolling_max', models.FloatField(blank=True, null=True)),
                ('drawdown', models.FloatField(blank=True, null=True)),
                ('asset_price', models.FloatField(blank=True, null=True)),
                ('price_diff_hl_bn', models.FloatField(blank=True, null=True)),
                ('colend_value', models.FloatField(blank=True, null=True)),
                ('aave_borrow_value', models.FloatField(blank=True, null=True)),
                ('aave_profit_value', models.FloatField(blank=True, null=True)),
                ('susds_eth_value', models.FloatField(blank=True, null=True)),
                ('susds_arbi_value', models.FloatField(blank=True, null=True)),
                ('cross_mtm_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['segment', 'date'], name='tracker_dai_segment_654d0e_idx')],
                'unique_together': {('date', 'segment')},
            },
        ),
    ]
