# Generated by Django 6.0.5 on 2026-05-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypnl',
            name='segment',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='segment',
            field=models.CharField(max_length=10),
        ),
    ]
