# Generated by Django 6.0.5 on 2026-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_dailypnl_segment_alter_snapshot_segment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['segment', '-timestamp'], name='tracker_sna_segment_ef4f74_idx'),
        ),
    ]
