# Generated by Django 6.0.5 on 2026-07-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_snapshot_binance_collateral'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='snapshot',
            name='tracker_sna_segment_ef4f74_idx',
        ),
    ]
