# Generated by Django 6.1 on 2026-09-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_snapshot_deribit_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='vault_positions_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='vault_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
